AtividadeAulaTarde/AtividadeAulaTarde/Models/CadCep.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtividadeAulaTarde.Models

{
    [Table("Endereco")]
    public class CadCep
    {
        [Key]
        public int Id { get; set; }
        public string Cep { get; set; }
        public string Logradouro { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Localidade { get; set; }
        public string Uf { get; set; }
    }
}

AtividadeAulaTarde/AtividadeAulaTarde/Models/Context.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace AtividadeAulaTarde.Models
{
    public class Context : DbContext
    {
        public DbSet<CadCep> Endereco { get; set; }
        public Context(DbContextOptions<Context> options) : base(options)
        {

        }
    }
}

AtividadeAulaTarde/AtividadeAulaTarde/Controllers/CepAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AtividadeAulaTarde.Models;
using AtividadeAulaTarde.DAO;

namespace AtividadeAulaTarde.Controllers
{
    [Route("api/Endereco")]
    [ApiController]
    public class CepAPIController : ControllerBase
    {


        //Iago Canez Medeiros ------ 1833441




        private readonly ConsultaDao _consultaDao;
        public CepAPIController(ConsultaDao consultaDao)
        {
            _consultaDao = consultaDao;
        }




        // GET: api/Endereco/ListarEnderecos
        [HttpGet]
        [Route("ListarEnderecos")]
        public List<CadCep> Listar()
        {
            return _consultaDao.Listar();
        }




        // GET: api/Endereco/ListarEndereco/{81730000}
        [HttpGet]
        [Route("ListarEndereco/{cep}")]
        public string ListarEndereco(string cep)
        {
            return _consultaDao.ListarEndereco(cep);
        
        }




        // POST: api/Endereco/CadastrarEndereco
        [HttpPost]
        [Route("CadastrarEndereco")]
        public IActionResult CadastrarEndereco(CadCep cadcep)
        {
            _consultaDao.Cadastrar(cadcep);

            return Created("", cadcep);
        }




        // PUT: api/Endereco/AlterarEndereco  
        [HttpPut]
        [Route("AlterarEndereco")]
        public void AlterarEndereco(CadCep cadCep)
        {
            _consultaDao.Atualizar(cadCep);

        }




        // DELETE: api/Endereco/DeletarEndereco/{id}
        [HttpDelete]
        [Route("DeletarEndereco/{id}")]
        public void DeletarEndereco(int id)
        {
            _consultaDao.Deletar(id);
        }


    }
}

AtividadeAulaTarde/AtividadeAulaTarde/Controllers/CepController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AtividadeAulaTarde.DAO;
using Newtonsoft.Json;
using System.Net;
using AtividadeAulaTarde.Models;

namespace AtividadeAulaTarde.Controllers

{


    //Iago Canez Medeiros ------ 1833441




    public class CepController : Controller 
    {
        private readonly ConsultaDao _consultaDao;
        public CepController(ConsultaDao consultaDao)
        {
            _consultaDao = consultaDao;
        }



        public IActionResult Index()
        {
            var model = _consultaDao.Listar();
            return View(model);
        }



        [HttpPost]
        public IActionResult ConsultaCep(string txtCep)
        {
            var url = $@"https://viacep.com.br/ws/{txtCep}/json/";

            WebClient client = new WebClient();

            TempData["Endereco"] = client.DownloadString(url);

            if (TempData["Endereco"] != null)
            {
                string result = TempData["Endereco"].ToString();
                TempData["Endereco"] = null;
                CadCep consulta = JsonConvert.DeserializeObject<CadCep>(result);
                consulta.Cep = consulta.Cep.Replace("-", "");
                _consultaDao.Cadastrar(consulta);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}
//Versão Final da Entrega

AtividadeAulaTarde/AtividadeAulaTarde/Views/Cep/Index.cshtml
@Model

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Concultar CEP</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

</head>
<body class="container" style="padding-top:60px">
    <div class="row col-xs-12 col-sm-12 col-md-12 col-lg-12" align="center">
        <h1>Consulta e Cadastro de CEP</h1>
    </div>

    <div class="container">
        <form asp-action="ConsultaCep" asp-controller="Cep">
            <label>Digite o CEP</label>
            <input type="text" id="txtCep" class="form-control col-4" name="txtCep" />
            <input type="submit" value="Consultar/Consultar" class="btn btn-info" />
        </form>
    </div>
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Cep</th>
                    <th scope="col">Logradouro</th>
                    <th scope="col">Complemento</th>
                    <th scope="col">Bairro</th>
                    <th scope="col">Localidade</th>
                    <th scope="col">UF</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Cep</td>
                        <td>@item.Logradouro</td>
                        <td>@item.Complemento</td>
                        <td>@item.Bairro</td>
                        <td>@item.Localidade</td>
                        <td>@item.Uf</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>